apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-spring-boot
  labels:
    app: hazelcast-spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-spring-boot
  template:
    metadata:
      labels:
        app: hazelcast-spring-boot
    spec:
      containers:
        - name: hazelcast-spring-container
          image: chapparavi22/hazelcast-spring-boot:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5701
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-boot-rest
spec:
  type: NodePort
  selector:
    app: hazelcast-spring-boot
  ports:
    - name: restport
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-boot-service
spec:
  type: LoadBalancer
  selector:
    app: hazelcast-spring-boot
  ports:
    - name: hazelport
      port: 5701